### ISSUE TITLE
Read me improvements?

### ISSUE THREAD

**Issue by ahmadawais** [ServerPress/ds-cli#1]
This sounds like something interesting. Can you update the readme file so that I can understand what it does and how? I mean from the looks of it, I cannot understand what it is. All the tools it mentioned, I already have installed on my Mac. I am worried if I install this one it will mess with them.

**Comment by bishless** [comment]
Yeah, I'm wondering if there's a missing composer install step or something.

I've installed DS-CLI in my DesktopServer 3.8.1 installation and get [these errors](https://cloudup.com/c1NskTeFd-m).

Looks like a `vendor` directory is missing from the zip that gets downloaded.

UPDATE: Nevermind, just found proper install instructions on the releases page, rather than just using the main download button. Couldn't hurt to add this advice to the main project readme.

**Comment by easternwawoman** [comment]
Where did you find "the releases page"?

**Comment by bishless** [comment]
Here you go.

https://github.com/ServerPress/ds-cli/releases

**Comment by easternwawoman** [comment]
Thank you.  Share: https://serverpress.com/desktopserver-ds-cli-command-line-interface/   I have the recent version.  My eyes did not see what they should have seen.  Silly eyes.  :-)
